// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgpWGNw4sAo70gKMu0ncR185KVh6eWoFo',
    appId: '1:854040750364:web:cc3c7a619926c07aff72d9',
    messagingSenderId: '854040750364',
    projectId: 'rideapp-67837',
    authDomain: 'rideapp-67837.firebaseapp.com',
    storageBucket: 'rideapp-67837.firebasestorage.app',
    measurementId: 'G-G9634S8JM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2a-jc7xjEywZU6WFkAN7YlZdv3U88d4',
    appId: '1:854040750364:android:1e6429777f2ba7a9ff72d9',
    messagingSenderId: '854040750364',
    projectId: 'rideapp-67837',
    storageBucket: 'rideapp-67837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuj2YVpYZdFGTuTT54drnB1O1176JLtk8',
    appId: '1:854040750364:ios:0dca442bb996d03eff72d9',
    messagingSenderId: '854040750364',
    projectId: 'rideapp-67837',
    storageBucket: 'rideapp-67837.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuj2YVpYZdFGTuTT54drnB1O1176JLtk8',
    appId: '1:854040750364:ios:0dca442bb996d03eff72d9',
    messagingSenderId: '854040750364',
    projectId: 'rideapp-67837',
    storageBucket: 'rideapp-67837.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppRider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgpWGNw4sAo70gKMu0ncR185KVh6eWoFo',
    appId: '1:854040750364:web:e8c58fa4516e2a8dff72d9',
    messagingSenderId: '854040750364',
    projectId: 'rideapp-67837',
    authDomain: 'rideapp-67837.firebaseapp.com',
    storageBucket: 'rideapp-67837.firebasestorage.app',
    measurementId: 'G-XR630M9Z74',
  );

}